[package]
name = "nifpga-apigen"
version = "0.1.5"
authors = ["David Taylor <david.baker.taylor@gmail.com>"]
edition = "2018"
description = "API generator for NI FPGAs"
license = "MIT"

[dependencies]
regex = "1.3.9"
clap = "2.33.1"